attitude: 1
distrust: 0.25
expected response_time in mins: 2
kinship: 0.67
negative experience count: 52
positive experience count: 12
predictor threshold: 0.45
missions worked together: 52
trust: 0.09
uncertainty: 0.66
